### ISSUE TITLE
Validating a 'good' url after validation a 'bad' url 

### ISSUE THREAD

**Issue by teunfransen** [SURFnet/Service-provider-registration#40]
The following does not happen always, but I added two metadata urls where it does occur.

When I enter a metadata url which is not valid (for whatever reason), remove the url and enter a url that is valid, the form does not always validate correctly. As if it caches the information from the first (invalid) url.

Workaround:
Remove the url, refresh the page, go back to metadata tab and enter the valid metadata url. Now it works.

'bad' url: https://mijnnhltest.nhl.nl/simplesaml/module.php/saml/sp/metadata.php/default-sp
good url: https://eur-acceptation.comradsdev.com/simplesaml/module.php/saml/sp/metadata.php/default-sp

**Comment by Tjeerd** [comment]
I've changed the flow of validating the form a bit, because this not an actual bug or caching issue, but rather a timing issue. The 'old' url was still being validated when you started pasting a new URL (because of the key combination CTRL+V), control keys (like CTRL or SHIFT) now no longer trigger the validation event.

Please check if this 'solves' your issue.
